"""Add authentication tables

Revision ID: 7a932ed594cf
Revises: 
Create Date: 2025-12-01 21:57:42.974623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a932ed594cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_email', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_contact_messages_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contact_messages_user_id', type_='foreignkey')
        batch_op.drop_column('verified_email')
        batch_op.drop_column('verification_level')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
